apiVersion: v1alpha1
kind: TrustedRootsConfig
name: custom-ca
certificates: |-
    -----BEGIN CERTIFICATE-----
    MIIFAjCCA+qgAwIBAgISBtR/OD6iPVQpYiKZLG2yZ68IMA0GCSqGSIb3DQEBCwUA
    MDMxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQD
    EwNSMTMwHhcNMjYwMTE2MTk1MzM3WhcNMjYwNDE2MTk1MzM2WjAXMRUwEwYDVQQD
    EwxpZGVhbGlzdGEucHQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCw
    seqQ4HYS0JahNq1xS1Tu14vZtsrqtrShQA42/1uKoTgwO2xpevIodZWppcCipBG9
    UqhhPu97AMp2pMH0XEEJj/NgASWOhkEQwSdCrKCDRq1gWa9YCDAP/Ysg7Rb88hjQ
    rWWFrXDvx73+OLeUMdO9h6+w9/e0tFoix7uYuIlOHHi8Jjf0V3ocHJTZ+9i8VmOj
    PmnQmD4w0H/M/n9Ohq1cN2wYupHaNiwNyuVEa2MQ1xx1sxZHKtuT5WWei9gikkee
    wC0GUksmuMFeh/wS0zXCN2O05BqN6228mW/FJBciaXNHQndQawvoyKI2NwkgiT2B
    vyxj66IlCUWbytSfSjLtAgMBAAGjggIqMIICJjAOBgNVHQ8BAf8EBAMCBaAwHQYD
    VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
    BBYEFGFzrNJnPOTm5CyIw+zzR6jnbcCNMB8GA1UdIwQYMBaAFOernw8sM6BT015P
    eMiyhA471pIzMDMGCCsGAQUFBwEBBCcwJTAjBggrBgEFBQcwAoYXaHR0cDovL3Ix
    My5pLmxlbmNyLm9yZy8wJwYDVR0RBCAwHoIOKi5pZGVhbGlzdGEucHSCDGlkZWFs
    aXN0YS5wdDATBgNVHSAEDDAKMAgGBmeBDAECATAtBgNVHR8EJjAkMCKgIKAehhxo
    dHRwOi8vcjEzLmMubGVuY3Iub3JnLzkuY3JsMIIBAwYKKwYBBAHWeQIEAgSB9ASB
    8QDvAHYAlpdkv1VYl633Q4doNwhCd+nwOtX2pPM2bkakPw/KqcYAAAGbyJRmzQAA
    BAMARzBFAiEAimFpeKTtbQ/XCRAV/U9AMfgOd2aadIp4JlC0rAFm9tYCIFlo+08B
    Wt4inI0A9CkpUgMjUpedMxd4yn2skhpvFVZXAHUAFoMtq/CpJQ8P8DqlRf/Iv8gj
    0IdL9gQpJ/jnHzMT9foAAAGbyJRqkQAABAMARjBEAiB7IFktSWQgmjh6ZcKT0RdM
    8/8OjTANEOFRRBltNytG4wIgESGUVnsjRQ5X/Qj4cJLVVDCA36YqVaZ2ZWYt+Akl
    WMYwDQYJKoZIhvcNAQELBQADggEBAAC/hoBazSGQB+wDLBcDUZjSrQfpp1irNL3q
    AnyxqZcRc7yRqfV1QJq4fzViz6Ak3D0KGox0+2IKdfVKc6Z/hbxlfaL94rBp6Hnu
    P81owmT2v0dpCEIGB3H2DqobtedG2EtlB5nrPESdroNHMrpJUeGG7Xtss5T7F3E9
    9T7vG+EUS1/EbMIJP9U6otR2xfrNw0eX/PzCwtGKwcl2VLMp+l+mLe3QLsGlECC5
    jFg8ejSueLPFWAyC25dTTMQHlARXs6pjY6wM1+faV9sOLhklQFQc1ylisVSAgn8q
    +X0+jMgXmSkzunZZB98bvylqFMzASiqY1cQw6ifp0FbuVABMya4=
    -----END CERTIFICATE-----
